---
title: "In silico data models"
author: "Mikkel Skjoldan Svenningsen"
date: "`r Sys.Date()`"
output: html_document
---

```{r import packages and functions, include=FALSE}
library(ggplot2)
library(ggpubr)
#library(MASS)
library(LMMstar)
library(mvtnorm)
library(MBESS)
library(here)
library(grid)
library(gtable)
library(patchwork)

rm(list = ls())

source("supporting_functions.R")

```

```{r 1.dcc_early, include=FALSE}

here::i_am("0_test_performance.Rmd")


labels = c("dcc_early", "dcc_late", "dvar_early", "dvar_late")

n_subjects <- 40
n_repeats <- 10

rn <- sample(1:100000,1)
  
  
  ### expected power
  
null_means <- c(1 ,1 ,1, 1)

for(label in labels){
  
  if(label == "dcc_early"){
    
    cor_matrix <- toeplitz(c(1,0.8,0.5, 0.2))
    cov_matrix <- cor_matrix
    sds <- diag(cov_matrix)
    sig_means <- c(1, 1.5, 1.5, 1.5)
    
    l_power <- get_power(cor_matrix, sds, sig_means, n_subjects)
  
  }else if(label=="dcc_late"){
    
    cor_matrix <- toeplitz(c(1,0.8,0.5, 0.2))
    cov_matrix <- cor_matrix
    sds <- diag(cov_matrix)
    sig_means <- c(1, 1, 1, 1.5)
    l_power <- get_power(cor_matrix, sds, sig_means, n_subjects)
    
  }else if(label=="dvar_early"){
    
    
    cc <- 0.5
    cor_matrix <- toeplitz(c(1,cc,cc, cc))
    sds <- seq(1,3,length=4)
    cov_matrix <- cor2cov(cor_matrix, sds)
    sig_means <- c(1, 1.5, 1.5, 1.5)
    l_power <- get_power(cor_matrix, sds, sig_means, n_subjects)

  
  
  }else if(label=="dvar_late"){
    
    
    cc <- 0.5
    cor_matrix <- toeplitz(c(1,cc,cc, cc))
    sds <- seq(1,3,length=4)
    cov_matrix <- cor2cov(cor_matrix, sds)
    sig_means <- c(1, 1, 1, 1.5)
    l_power <- get_power(cor_matrix, sds, sig_means, n_subjects)

   
    
  }
  
  sig_fraction <- 0.5
  
  df_res <- generate_datasets(n_subjects, cov_matrix, n_repeats, sig_fraction, sig_means, null_means)
  
  res <- run_tests(df_res)
  
  df_plot <- get_rates(res)
  
  df_plot$l_power <- l_power
  
  data_path <- here( "Numerical_data", "test_performance")
  
  saveRDS(df_res, paste0(data_path, "/df_numerical_data_", label,"_", rn, ".rds"))
  saveRDS(df_plot, paste0(data_path, "/df_plot_", label,"_", rn, ".rds"))

}

```



```{r plot results,  include=FALSE}


library(patchwork)


numbers <- c("13535")#, "6580")



dfs <- list()
for(cov_type in c("dvar", "dcc")){
  for(res_type in c("early", "late")){
    df_plot_1 <-  readRDS(paste0(data_path, "/df_plot_", cov_type, "_", res_type,"_",numbers[1],".rds"))
    dfs[[paste0(cov_type,"_",res_type)]] <- df_plot_1
  }
}



  
p1 <- ggplot(dfs[["dvar_early"]]) + 
  geom_line(aes(x=x, y=fpr_un, group=1), color='blue') + 
  geom_line(aes(x=x, y=fpr_cs, group=1), color='red') + 
    geom_point(aes(x=x, y=fpr_un, group=1), color='blue') + 
  geom_point(aes(x=x, y=fpr_cs, group=1), color='red') + 
  theme_bw() + ggtitle("M1 C2") + 
  labs(x = "Statistical test", y="False positive rate") + 
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    axis.text.x = element_text(color = "black"),
    axis.text.y = element_text(color = "black")
  ) + 
  geom_hline( yintercept = 0.05, linetype = "dashed" )


p2 <- ggplot(dfs[["dvar_early"]]) + 
  geom_line(aes(x=x, y=tpr_un, group=1), color='blue') + 
  geom_line(aes(x=x, y=tpr_cs, group=1), color='red') + 
  geom_line(data=dfs[[1]],aes(x=x, y=l_power, group=1), color='black' ) + 
  geom_point(aes(x=x, y=tpr_un, group=1), color='blue') + 
  geom_point(aes(x=x, y=tpr_cs, group=1), color='red') +
  geom_point(data=dfs[[1]],aes(x=x, y=l_power, group=1), color='black' ) + 
  theme_bw() + ggtitle("M2 C2") + 
  labs(x = "Statistical test", y="True positive rate")+ 
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    axis.text.x = element_text(color = "black"),
    axis.text.y = element_text(color = "black")
  ) 


p3 <- ggplot(dfs[["dvar_late"]]) + 
  geom_line(aes(x=x, y=fpr_un, group=1), color='blue') + 
  geom_line(aes(x=x, y=fpr_cs, group=1), color='red') + 
    geom_point(aes(x=x, y=fpr_un, group=1), color='blue') + 
  geom_point(aes(x=x, y=fpr_cs, group=1), color='red') + 
  theme_bw() + ggtitle("M1 C2")  + 
  labs(x = "Statistical test", y="False positive rate")+ 
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    axis.text.x = element_text(color = "black"),
    axis.text.y = element_text(color = "black")
  ) + 
  geom_hline( yintercept = 0.05, linetype = "dashed" )


p4 <- ggplot(dfs[["dvar_late"]]) + 
  geom_line(aes(x=x, y=tpr_un, group=1), color='blue') + 
  geom_line(aes(x=x, y=tpr_cs, group=1), color='red') + 
  geom_line(data=dfs[[2]],aes(x=x, y=l_power, group=1), color='black' ) + 
  geom_point(aes(x=x, y=tpr_un, group=1), color='blue') + 
  geom_point(aes(x=x, y=tpr_cs, group=1), color='red') + 
  geom_point(data=dfs[[2]],aes(x=x, y=l_power, group=1), color='black' ) + 
  theme_bw() + ggtitle("M3 C2")  +
  labs(x = "Statistical test", y="True positive rate")+ 
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    axis.text.x = element_text(color = "black"),
    axis.text.y = element_text(color = "black")
  )



p5 <- ggplot(dfs[["dcc_early"]]) + 
  geom_line(aes(x=x, y=fpr_un, group=1), color='blue') + 
  geom_line(aes(x=x, y=fpr_cs, group=1), color='red') + 
  geom_point(aes(x=x, y=fpr_un, group=1), color='blue') + 
  geom_point(aes(x=x, y=fpr_cs, group=1), color='red') + 
  theme_bw() + ggtitle("M1 C1")  + 
  labs(x = "Statistical test", y="False positive rate")+ 
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    axis.text.x = element_text(color = "black"),
    axis.text.y = element_text(color = "black")
  )+ geom_hline( yintercept = 0.05, linetype = "dashed" )


p6 <- ggplot(dfs[["dcc_early"]]) + 
  geom_line(aes(x=x, y=tpr_un, group=1), color='blue') + 
  geom_line(aes(x=x, y=tpr_cs, group=1), color='red') +
    geom_line(data=dfs[[3]],aes(x=x, y=l_power, group=1), color='black' ) + 
   geom_point(aes(x=x, y=tpr_un, group=1), color='blue') + 
  geom_point(aes(x=x, y=tpr_cs, group=1), color='red') +
    geom_point(data=dfs[[3]],aes(x=x, y=l_power, group=1), color='black' ) + 
  theme_bw() + ggtitle("M2 C1")+ 
  labs(x = "Statistical test", y="True positive rate")+ 
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    axis.text.x = element_text(color = "black"),
    axis.text.y = element_text(color = "black")
  )



p7 <- ggplot(dfs[["dcc_late"]]) + 
  geom_line(aes(x=x, y=fpr_un, group=1), color='blue') + 
  geom_line(aes(x=x, y=fpr_cs, group=1), color='red') + 
    geom_point(aes(x=x, y=fpr_un, group=1), color='blue') + 
  geom_point(aes(x=x, y=fpr_cs, group=1), color='red') + 
  theme_bw() + ggtitle("M1 C1")  + 
  labs(x = "Statistical test", y="False positive rate")+ 
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    axis.text.x = element_text(color = "black"),
    axis.text.y = element_text(color = "black")
  )+ geom_hline( yintercept = 0.05, linetype = "dashed" )


p8 <- ggplot(dfs[["dcc_late"]]) + 
  geom_line(aes(x=x, y=tpr_un, group=1), color='blue') + 
  geom_line(aes(x=x, y=tpr_cs, group=1), color='red') + 
      geom_line(data=dfs[[4]],aes(x=x, y=l_power, group=1), color='black' ) + 
    geom_point(aes(x=x, y=tpr_un, group=1), color='blue') + 
  geom_point(aes(x=x, y=tpr_cs, group=1), color='red') + 
      geom_point(data=dfs[[4]],aes(x=x, y=l_power, group=1), color='black' ) +
  theme_bw() + ggtitle("M3 C1")+ 
  labs(x = "Statistical test", y="True positive rate")+ 
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(), 
    axis.text.x = element_text(color = "black"),
    axis.text.y = element_text(color = "black")
  )




set_panel_size <- function(p,
                           width = unit(5, "cm"),
                           height = unit(5, "cm")) {
  gt <- ggplotGrob(p)

  panel_ids <- grep("^panel", gt$layout$name)

  gt$widths[unique(gt$layout$l[panel_ids])]  <- width
  gt$heights[unique(gt$layout$t[panel_ids])] <- height

  patchwork::wrap_elements(full = gt)
}
#plots <- list(p1, p3, p5, p7, p2, p4, p6, p8)

plots <- list(p5, p6, p8, p1, p2, p4)

plots_fixed <- lapply(
  plots,
  function(p) set_panel_size(p, width = unit(6, "cm"), height = unit(6, "cm"))
)
main_plot_fixed <- wrap_plots(
  plots_fixed,
  ncol = 3
)


data_path <- here( "Figures")


ggsave(plot = main_plot_fixed, filename= paste0(data_path, "/rates_plot_new.pdf"), width=14, height=6)




```





