---
title: "In silico data models"
author: "Mikkel Skjoldan Svenningsen"
date: "`r Sys.Date()`"
output: html_document
---






```{r define data generating function, include=FALSE}
library(ggplot2)
library(ggpubr)
library(MASS)
library(LMMstar)
library(mvtnorm)
library(lavaSearch2)
library(nlme)
library(foreach)
library(doParallel)
library(compiler)
library(foreach)
library(doParallel)
library(mmrm)
library(here)
rm(list = ls())
source("supporting_functions_2.R")
here::i_am("2_small_samples_ttest.Rmd")

```


```{r define data generating function, include=FALSE}
library(MBESS)

cc <- 0.5

cor_matrix <- toeplitz(c(1,cc,cc, cc))
sds <- seq(1,3,length=4)

sig_fraction <- 0.5

cov_matrix <- cor2cov(cor_matrix, sds)

sig_means <- c(1, 1.5, 1.5, 1.5) # 0.35
null_means <- c(1 ,1 ,1, 1)

n_repeats <- 10000


Ns <- c(10,15,20,25)



for(N in Ns){
  df_list <- generate_datasets(N, cov_matrix, n_repeats, sig_fraction, sig_means, null_means)

  df_fit <- run_tests_noPBS(df_list, N, cov_matrix, n_repeats, sig_fraction, sig_means, null_means)

  df_rates <- results_to_rates_small_sample(df_fit)
  
  data_path <- here(  "Numerical_data", "small_samples_ttest")

  saveRDS(df_rates, paste0(data_path, "/df_rates_dvar_N=", N, "_n_repeats=", n_repeats, ".rds"))
  saveRDS(df_fit, paste0(data_path, "/df_fit_rates_dvar_N=", N, "_n_repeats=", n_repeats, ".rds"))
}
```


```{r plot tt, dvar, include=FALSE}

data_path <- here(  "Numerical_data", "small_samples_ttest")
n_subjects <- c("10", "15", "20", "25")
files <- paste0(data_path, "/df_fit_rates_dvar_N=", n_subjects, "_n_repeats=10000.rds")


contrasts <- c("12", "13", "14", "23", "24", "34")

df_plot <- do.call(rbind, lapply(files, function(file_i){
  
  df_i <- readRDS(file_i)
  
  fpr <- sapply(contrasts, function(contrast_i){
    pv <- df_i[[paste0("pv_t", contrast_i, "_un")]]
    mean(pv[!is.na(pv) & !df_i$sh_out] <= 0.05)
    
  }) # fpr sapply
  
  tpr <- sapply(contrasts, function(contrast_i){
    pv <- df_i[[paste0("pv_t", contrast_i, "_un")]]
    mean(pv[!is.na(pv) & df_i$sh_out] <= 0.05)
    
  }) # fpr sapply
  

  data.frame(
  
  setNames(as.list(fpr), paste0("fpr_un_t", contrasts)), 
  setNames(as.list(tpr), paste0("tpr_un_t", contrasts))
  
  )
})) #do.call



df_plot$x = c(10,15, 20,25)

rownames(df_plot) <- df_plot$x

lop <- list()

for( i in 1:4 ){
  
  df_sub <- data.frame(x = 1:6, fpr = as.numeric(df_plot[i, 1:6]), tpr = as.numeric(df_plot[i, 7:12]))

g <- ggplot(df_sub) + 
  geom_line(aes(x=x, y=fpr, color="False positive rate")) + 
  geom_line(aes(x=x, y=tpr, color="True positive rate")) + 
  geom_point(aes(x=x, y=fpr, color="False positive rate")) + 
  geom_point(aes(x=x, y=tpr, color="True positive rate")) + 
  theme_bw() + 
  geom_hline(yintercept = 0.05, linetype = "dashed") + 
  scale_color_manual( 
  name = "", 
  values = c( 
           "False positive rate" = "steelblue", 
           "True positive rate" = "red4")) + 

  ggtitle(paste0("N = ", df_plot$x[i])) + ylim(0, 0.4) + 
  scale_x_continuous(breaks = 1:6, labels = c("1vs2", "1vs3", "1vs4", "2vs3", "2vs4", "3vs4")) +
  theme(
  panel.border = element_rect(colour = "black", fill = NA, linewidth = 0.5),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_blank(), 
  text = element_text(size = 9), 
  legend.text = element_text(size = 12)
)

  #if(i == 1){
    g <- g +   labs(x="Time/site", y ="Significance rate") 
  #}else{
  #  g <- g +   labs(x="Time/site", y ="") 
    
  #}

  lop[[ i ]] <- g 


}


g_combined <- ggarrange(lop)

g <- ggarrange(lop[[1]], lop[[2]], lop[[3]], lop[[4]],
               common.legend = TRUE, ncol=4, 
               legend = "bottom")+ theme(panel.border = element_blank())

data_path <- here( "Figures")
ggsave(plot = g, filename= paste0(data_path, "/small_samples_ttest.pdf"), width=8, height=3)


```
